### ISSUE TITLE
where is cifar10_trainval_idx.npy?

### ISSUE THREAD

**Issue by GaengSu** [swyoon/normalized-autoencoders#1]
안녕하세요. TFKR 글을 통해 좋은 논문을 읽게 되었습니다.

논문이 흥미로워서 sample code를 돌려보려했는데, datasets/cifar10_trainval_idx.npy가 존재하지 않아 정상 실행이 되지 않고있습니다.

파일이 추후 공유되는지, 혹은 제가 잘못한 점이 있는지 알려주시면 감사하겠습니다.😊

-------------------

I tried to run this sample code, but cifar10_trainval_idx.npy file does not exist, so it dosn't run. 

Please let me know if the file will be shared later or if there is anything I did wrong.

**Comment by swyoon** [comment]
@GaengSu 알려주셔서 감사합니다! 저의 착오로 해당 데이터들이 누락되어 있었습니다. 현재 [드롭박스 링크](https://www.dropbox.com/sh/u41ewgwujuvqvpm/AABM6YbklJFAruczJPhBWNwZa?dl=0) 에 업로드해두었습니다!

------
The missing files are now available via the [dropbox link](https://www.dropbox.com/sh/u41ewgwujuvqvpm/AABM6YbklJFAruczJPhBWNwZa?dl=0).

It was my bad. Thank you for letting me know!
