### ISSUE TITLE
Divergence of CD/PCD

### ISSUE THREAD

**Issue by GloryyrolG** [swyoon/normalized-autoencoders#11]
Hi Sangwoong @swyoon ,

As you reported the results of CD/PCD counterparts (e.g., Table 1), did you successfully tune to train the EBMs by these algorithms? I cannot make it. The model diverges soon. How did you make it?

Just after several hundred iterations, the energy is like (white one),

![image](https://user-images.githubusercontent.com/33202229/152456816-42b442f4-0261-4164-851c-223f18c3ce49.png)

the sample is like,

![image](https://user-images.githubusercontent.com/33202229/152456889-d19938c0-adda-4f80-abcf-03f00c81fdf9.png)

Thanks.

**Comment by GloryyrolG** [comment]
I used standard hyperparam settings as in IGEBM, i.e., `step = 60`, `step_size = 10`, `noise_std = 0.005`, `clip_langevin_grad = 0.01`.

**Comment by swyoon** [comment]
Dear @GloryyrolG , Sorry for the late update.

From my experience, NAE for **image data** could not be successfully trained using CD or PCD as in IGEBM.
My guess is that the energy landscape of NAE is significantly more rigged than that of IGEBM and have much more local optima. 
Therefore, MCMC chain in the input space does not effectively explore possible samples from the model.
On-manifold initialization is hence essential for training NAE for complex, high-dimensional data like images.
Hope this helps.
