### ISSUE TITLE
Noise Annealing with the Step Size

### ISSUE THREAD

**Issue by GloryyrolG** [swyoon/normalized-autoencoders#12]
Hi Sangwoong @swyoon ,

Shouldn't it be more standard to anneal noise together with `step_size` since they are actually coupled (`step_size \propto noise^2` ([Welling & Teh, 2011](https://www.stats.ox.ac.uk/~teh/research/compstats/WelTeh2011a.pdf)))? Or you want the sampling to be more biased in practice?

https://github.com/swyoon/normalized-autoencoders/blob/27ccb74bb725768f9ba9ea6fa03a7a40867eebb1/models/langevin.py#L146

Always thanks.

**Comment by swyoon** [comment]
Dear @GloryyrolG , 
Always thank you for your good questions. 
You are right that the noise annealing is not coupled to the step size. That noise annealing procedure is not a standard one.
The rationale is to make the Lagevin Monte Carlo more close to gradient descent by reducing the noise.
It is basically a heuristic, and it is okay to fix the noise to a small magnitude.
