### ISSUE TITLE
some key word missing

### ISSUE THREAD

**Issue by GaengSu** [swyoon/normalized-autoencoders#3]
안녕하세요. 저번에 말씀드린 부분 중 일부가 수정이 되지 않은 것 같습니다.
train.py 57 line의 clip_grad와 nae.py 39 line의 small_lr_D 부분은 아직 남아있는데, yml파일에는 두 keyword가 존재하지 않아 run이 안되고 있습니다.

**Comment by swyoon** [comment]
안녕하세요. 응답이 늦어 죄송합니다 (ㅠㅠ)
지금 제가 새로 체크아웃 받아서 새로 돌려보고 있는데요, 제가 README.md에 적어놓은 커맨드가 제 환경에서는 일단 실행이 잘 되고 있습니다.
혹시 가장 최신 버젼의 코드로 업데이트 되었는지 확인 가능하실까요?

train.py의 Line 57에서는 현재 `get('clip_grad', None)` 으로 되어 있기 때문에, `clip_grad`가 없으면 `None`이 자동으로 반환되게 되어 있습니다.
https://github.com/swyoon/normalized-autoencoders/blob/0c77f7e29289e336c0fe5e941aaec8baa4a4fb82/train.py#L57

관련하여 문제 상황을 조금 더 자세히 알려주시면 제가 해결하는 데에 도움이 더 될 것 같습니다!

**Comment by GaengSu** [comment]
> 안녕하세요. 응답이 늦어 죄송합니다 (ㅠㅠ)
> 지금 제가 새로 체크아웃 받아서 새로 돌려보고 있는데요, 제가 README.md에 적어놓은 커맨드가 제 환경에서는 일단 실행이 잘 되고 있습니다.
> 혹시 가장 최신 버젼의 코드로 업데이트 되었는지 확인 가능하실까요?
> 
> train.py의 Line 57에서는 현재 `get('clip_grad', None)` 으로 되어 있기 때문에, `clip_grad`가 없으면 `None`이 자동으로 반환되게 되어 있습니다.
> https://github.com/swyoon/normalized-autoencoders/blob/0c77f7e29289e336c0fe5e941aaec8baa4a4fb82/train.py#L57
> 
> 관련하여 문제 상황을 조금 더 자세히 알려주시면 제가 해결하는 데에 도움이 더 될 것 같습니다!

정상 작동하는 것 확인했습니다. 감사합니다!
